apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-lb
  template:
    metadata:
      labels:
        app: testing-lb
    spec:
      containers:
      - name: testing-lb
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testing-lb
spec:
  selector:
    app: testing-lb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-lb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testing-lb
            port:
              number: 80
